language: scala
sudo: false
jdk: openjdk8
scala:
- 2.12.11
- 2.13.1
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}" test "scalaParser/testOnly scalaparser.SnippetSpec"
matrix:
  include:
  - scala: 2.12.11
    jdk: openjdk11
    dist: xenial
